### ISSUE TITLE
Meta data information is required

### ISSUE THREAD

**Issue by sebayaki** [Steemhunt/hunt-town#2]
![image](https://user-images.githubusercontent.com/1332279/202988253-f31aaae1-224a-4f23-8a61-c82feabe32f8.png)

![image](https://user-images.githubusercontent.com/1332279/202988273-751a8521-b1f2-4764-922b-a8846ae7f7c9.png)

- [x] Background image for the collection page
- [x] Logo image for the collection page
- [x] Description for the collection page
- [x] Description for individual NFT page

Others for web repo:
- [x] og images
- [x] favicon
- [x] meta title, description

**Comment by realproject7** [comment]
OpenSea and og images - https://www.dropbox.com/sh/xsiqk0nbkhctxsi/AAApnJQ22weTgm9FHi6cTn5wa?dl=0

**Comment by realproject7** [comment]
[Collection desc]
ex_https://opensea.io/collection/rarepass-genesis

Hunt Town is a Web3 builders guild where builders come together to contribute to the expansion of Web3 culture and products. To become a member of the guild, you need at least 1 HUNT Building NFT. You can mint a HUNT Building NFT by locking up 1,000 HUNT tokens via the https://hunt.town/ official website.


[Individual edition desc]
ex_ https://opensea.io/assets/ethereum/0xbbb62c4b8ed027530ce5f6663d1a2aa8a7e8cacf/144

Hunt Town: Hunt Town is a Web3 builders guild where builders come together to contribute to the expansion of Web3 culture and products.

Building NFT: Minting of 1 HUNT Building NFT requires 1,000 HUNT tokens to be locked-up for one year. After this lock-up period, the NFT holder can burn his/her Building NFT and the 1,000 HUNT tokens will be returned to the person.

To have full access to the Hunt Town Discord and earn BUILD points, you need at least 1 Building NFT and to become verified via the Discord server.

About Hunt Town: https://hunt.town/
Hunt Town Discord: ---link---


[Hunt Town OpenSea profile desc]
Ex_ https://opensea.io/RarePass

Hunt Town is a Web3 builders guild where builders come together to contribute to the expansion of Web3 culture and products.


[Title]
Hunt Town, a Web3 builders guild


[Description]


Hunt Town is a Web3 builders guild where builders come together to contribute to the expansion of Web3 culture and products.
